import React from "react";
import Req_Res from "./Req_Res";

function Lead() {
  const statement =
    "Get leaderboard and current rank based on the scores -- Dont worry result will be based on users whom will be segragated based upon project property - ( Supports multi projects ! )  !";
  const req = [
    "{",
    '  "range": 2,',
    "}",
  ];
  const res = [
    "{",
    '    "statusCode": 200,',
    '    "data": {',
    '        "users": [',
    '        {',
    '            "_id": "665eedc0ad----403cfa",',
    '            "username": "shing1sks",',
    '            "project": "test",',
    '            "score": 10,',
    '            "rank": 1,',
    "        },",
    '        {',
    '            "_id": "66----c0ad----403cfa",',
    '            "username": "shing1sks",',
    '            "project": "test",',
    '            "score": 5,',
    '            "rank": 2,',
    "        },",
    '        "specificUser": {',
    '            "_id": "665eedc0ad32eae0af403cfa",',
    '            "username": "shing2sks",',
    '            "project": "test",',
    '            "score": 5,',
    '            "likes": [],',
    '            "comments": [],',
    '            "posts": [],',
    '            "followers": []',
    "        }",
    '        "rank": 2,',
    "    },",
    '    "message": "leaderboard fetched",',
    '    "success": true',
    "}",
  ];
  const type = "GET";
  const userModel = [
    "User",
    "username",
    "project",
    "fullname",
    "password",
    "email",
    "refreshtoken",
    "score",
    "avatar",
    "userdata",
    "likes",
    "comments",
    "posts",
    "followers",
    "createdAt",
    "updatedAt",
  ];
  const userCode = [
    "const schema = new mongoose.Schema(",
    "  {",
    "    username: {",
    "      type: String,",
    "      required: [true, 'Please provide a username'],",
    "      unique: true,",
    "      lowercase: true,",
    "      trim: true,",
    "      index: true,",
    "    },",
    "    project: {",
    "      type: String,",
    "      required: [true, 'Please provide a project name'],",
    "      lowercase: true,",
    "      trim: true,",
    "      index: true,",
    "    },",
    "    fullname: {",
    "      type: String,",
    "      required: [true, 'Please provide a fullname'],",
    "      lowercase: true,",
    "      trim: true,",
    "      index: true,",
    "    },",
    "    password: {",
    "      type: String,",
    "      required: [true, 'Please provide a password'],",
    "    },",
    "    email: {",
    "      type: String,",
    "      lowercase: true,",
    "      trim: true,",
    "    },",
    "    refreshtoken: {",
    "      type: String,",
    "    },",
    "    score: {",
    "      type: Number,",
    "      default: 0,",
    "    },",
    "    avatar: {",
    "      type: String,",
    "    },",
    "    userdata: {",
    "      type: Object,",
    "    },",
    "    likes: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Post' }],",
    "    comments: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Comment' }],",
    "    posts: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Post' }],",
    "    followers: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],",
    "  },",
    "  { timestamps: true }",
    ");",
  ];
  const endpoint = "http://localhost:8000/api/user/leaderboard";
  return <Req_Res statement={statement} type={type} req={req} res={res} model={userModel} endpoint={endpoint} code={userCode} />;
}

export default Lead;
