import React from "react";
import Req_Res from "./Req_Res.jsx";

function UserReg() {
  const statement =
    "Register a new user after register the user will be automatically have the login state !";
  const req = [
    "{",
    '  "username": "shingsks",',
    '  "fullname": "shreyash kumar singh",',
    '  "project": "test",',
    '  "password": "test123"',
    '  "avatar": "imagefile!",',
    "}",
  ];
  const res = [
    "{",
    '    "statusCode": 200,',
    '    "data": {',
    '        "user": {',
    '            "_id": "665eedc0ad----403cfa",',
    '            "username": "shing2sks",',
    '            "project": "test",',
    '            "fullname": "shreyash kumar singh",',
    '            "email": "",',
    '            "score": 0,',
    '            "avatar": "http://res.cloudinary.com/----/image/upload/-----/-----jpg",',
    '            "likes": [],',
    '            "comments": [],',
    '            "posts": [],',
    '            "followers": [],',
    '            "createdAt": "2024-06-04T10:34:40.735Z",',
    '            "updatedAt": "2024-06-04T10:34:40.993Z",',
    '            "__v": 0,',
    '            "refreshtoken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjVlZWRjMGFkMzJlYWUwYWY0MDNjZmEiLCJpYXQiOjE3MmV4cCI6MTcxODM2MTI4MH0.jWdj07zubK4wAuVYiUvWkv9V3eVItUnvq9LN_htbyjU"',
    "        },",
    '        "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjVlZWRjMGFkMzJlYWUwYWY0MDNjZmEiLCJwcm9qZWN0IjoidGxuYW1lIjoic2hyZXlhc2gga3VtYXIgc2luZ2giLCJlbWFpbCI6IiIsImlhdCI6MTcxNzQ5NzI4MCwiZXhwIjoxNzE3NTgzNjgwfQ.pTx30c2oGJx7zPyDyx1rDlyGVfDUqzL_aBW1CRwr05U",',
    '        "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjVlZWRjMGFkMzJlYWUwYWY0MDNjZmEiLCJpYXQiODAsImV4cCI6MTcxODM2MTI4MH0.jWdj07zubK4wAuVYiUvWkv9V3eVItUnvq9LN_htbyjU"',
    "    },",
    '    "message": "user created",',
    '    "success": true',
    "}",
  ];
  const type = "POST";
  const userModel = [
    "User",
    "username",
    "project",
    "fullname",
    "password",
    "email",
    "refreshtoken",
    "score",
    "avatar",
    "userdata",
    "likes",
    "comments",
    "posts",
    "followers",
    "createdAt",
    "updatedAt",
  ];
  const userCode = [
    "const schema = new mongoose.Schema(",
    "  {",
    "    username: {",
    "      type: String,",
    "      required: [true, 'Please provide a username'],",
    "      unique: true,",
    "      lowercase: true,",
    "      trim: true,",
    "      index: true,",
    "    },",
    "    project: {",
    "      type: String,",
    "      required: [true, 'Please provide a project name'],",
    "      lowercase: true,",
    "      trim: true,",
    "      index: true,",
    "    },",
    "    fullname: {",
    "      type: String,",
    "      required: [true, 'Please provide a fullname'],",
    "      lowercase: true,",
    "      trim: true,",
    "      index: true,",
    "    },",
    "    password: {",
    "      type: String,",
    "      required: [true, 'Please provide a password'],",
    "    },",
    "    email: {",
    "      type: String,",
    "      lowercase: true,",
    "      trim: true,",
    "    },",
    "    refreshtoken: {",
    "      type: String,",
    "    },",
    "    score: {",
    "      type: Number,",
    "      default: 0,",
    "    },",
    "    avatar: {",
    "      type: String,",
    "    },",
    "    userdata: {",
    "      type: Object,",
    "    },",
    "    likes: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Post' }],",
    "    comments: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Comment' }],",
    "    posts: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Post' }],",
    "    followers: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],",
    "  },",
    "  { timestamps: true }",
    ");",
  ];
  const endpoint = "http://localhost:8000/api/user/register";
  return <Req_Res statement={statement} type={type} req={req} res={res} model={userModel} endpoint={endpoint} code={userCode} />;
}

export default UserReg;
